### ISSUE TITLE
RSMP::NotReady when running equipment tests

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#114]
When running tests against an EC-3,  a number of tests fails with RSMP::NotReady. This should be investigated.

```
 10) Traffic Light Controller Detector Logic forcing is set with M0008
      Failure/Error: @site.unsubscribe_to_status Validator.config['main_component'], unsubscribe_list
      
      RSMP::NotReady:
        RSMP::NotReady
      # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.2.1/lib/rsmp/site_proxy.rb:241:in `unsubscribe_to_status'
      # ./spec/support/status_helpers.rb:61:in `ensure in block in wait_for_status'
      # ./spec/support/status_helpers.rb:61:in `block in wait_for_status'
      # ./spec/support/log_helpers.rb:5:in `log_confirmation'
      # ./spec/support/status_helpers.rb:53:in `wait_for_status'
      # ./spec/support/command_helpers.rb:435:in `switch_detector_logic'
      # ./spec/site/tlc/detector_logics_spec.rb:47:in `block (5 levels) in <top (required)>'
      # ./spec/support/testee.rb:32:in `block in connected'
      # ./spec/support/testee.rb:101:in `block in within_reactor'
      # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:260:in `block in make_fiber'
      # ------------------
      # --- Caused by: ---
      # Async::TimeoutError:
      #   execution expired
      #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:66:in `yield'
```

**Comment by emiltin** [comment]
Most examples fail with the backtrace above, but there one with:

```
6) Traffic Light Controller Clock is used for aggregated status timestamp
     Failure/Error:
       result = @site.send_command component, command_list, collect: {
           timeout: Validator.config['timeouts']['command_response']
         }

     RSMP::NotReady:
       RSMP::NotReady
     # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.2.1/lib/rsmp/site_proxy.rb:272:in `send_command'
     # ./spec/support/command_helpers.rb:5:in `block in send_command_and_confirm'
     # ./spec/support/log_helpers.rb:5:in `log_confirmation'
     # ./spec/support/command_helpers.rb:4:in `send_command_and_confirm'
     # ./spec/support/command_helpers.rb:337:in `reset_clock'
     # ./spec/support/command_helpers.rb:344:in `ensure in with_clock_set'
     # ./spec/support/command_helpers.rb:344:in `with_clock_set'
     # ./spec/site/tlc/clock_spec.rb:130:in `block (4 levels) in <top (required)>'
     # ./spec/support/testee.rb:32:in `block in connected'
     # ./spec/support/testee.rb:101:in `block in within_reactor'
     # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:260:in `block in make_fiber'
     # ------------------
     # --- Caused by: ---
     # Async::TimeoutError:
     #   execution expired
     #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.1/lib/async/task.rb:66:in `yield'
```

**Comment by emiltin** [comment]
possible relation to #92?

**Comment by emiltin** [comment]
i suspect this is related to disconnect/reconnects happening while a test is waiting for some kind of response. in the case of ITC-3, disconnects happen because a Watchdog is not received within the configured timeout, see https://github.com/rsmp-nordic/rsmp_implementations/issues/14

**Comment by emiltin** [comment]
> i suspect this is related to a disconnect/reconnect happening while a test is waiting for some kind of response.

confirmed. when a site disconnects and reconnects, using the old site object to send a message causes a NotReady error.

**Comment by emiltin** [comment]
i expect the merged PR to fix the NotReady errors, but let's see. however a disconnect can probably still cause tests to fail with other errors

**Comment by emiltin** [comment]
fix is confirmed to work
