### ISSUE TITLE
refactor command spec

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#15]
I've refactored the command spec to reduce code duplication.
 It works as far as I can tell with the Dynniq tcl, but does not seem to repond to functional position.

Can you try it with a Swarco tlc?

It's in the branch 'refactor'

**Comment by otterdahl** [comment]
The branch 'refactor' produces the following output:
```
FFF

Failures:

  1) RSMP site commands M0001 set yellow flash
     Failure/Error: expect { yield task, @supervisor, @remote_site }.to_not raise_error
     
       expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `+'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `reset'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:29:in `initialize'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `new'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `after'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:259:in `with_timeout'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/probe.rb:49:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/archive.rb:50:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/site_proxy.rb:229:in `wait_for_command_response'
         # ./spec/site/command_spec.rb:74:in `block in set_functional_position'
         # ./spec/site/command_spec.rb:7:in `log_confirmation'
         # ./spec/site/command_spec.rb:73:in `set_functional_position'
         # ./spec/site/command_spec.rb:121:in `switch_yellow_flash'
         # ./spec/site/command_spec.rb:180:in `block (3 levels) in <top (required)>'
         # ./spec/support/test_site.rb:71:in `block (2 levels) in connected'
         # ./spec/support/test_site.rb:71:in `block in connected'
         # ./spec/support/test_site.rb:16:in `block in within_reactor'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  2) RSMP site commands M0001 set dark mode
     Failure/Error: expect { yield task, @supervisor, @remote_site }.to_not raise_error
     
       expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `+'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `reset'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:29:in `initialize'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `new'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `after'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:259:in `with_timeout'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/probe.rb:49:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/archive.rb:50:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/site_proxy.rb:229:in `wait_for_command_response'
         # ./spec/site/command_spec.rb:74:in `block in set_functional_position'
         # ./spec/site/command_spec.rb:7:in `log_confirmation'
         # ./spec/site/command_spec.rb:73:in `set_functional_position'
         # ./spec/site/command_spec.rb:129:in `switch_dark_mode'
         # ./spec/site/command_spec.rb:191:in `block (3 levels) in <top (required)>'
         # ./spec/support/test_site.rb:71:in `block (2 levels) in connected'
         # ./spec/support/test_site.rb:71:in `block in connected'
         # ./spec/support/test_site.rb:16:in `block in within_reactor'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  3) RSMP site commands M0002 set time plan
     Failure/Error: expect { yield task, @supervisor, @remote_site }.to_not raise_error
     
       expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `+'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `reset'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:29:in `initialize'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `new'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `after'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:259:in `with_timeout'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/probe.rb:49:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/archive.rb:50:in `capture'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-18897d195ae8/lib/rsmp/site_proxy.rb:229:in `wait_for_command_response'
         # ./spec/site/command_spec.rb:44:in `block in set_plan'
         # ./spec/site/command_spec.rb:7:in `log_confirmation'
         # ./spec/site/command_spec.rb:43:in `set_plan'
         # ./spec/site/command_spec.rb:96:in `switch_plan'
         # ./spec/site/command_spec.rb:201:in `block (4 levels) in <top (required)>'
         # ./spec/site/command_spec.rb:201:in `each'
         # ./spec/site/command_spec.rb:201:in `block (3 levels) in <top (required)>'
         # ./spec/support/test_site.rb:71:in `block (2 levels) in connected'
         # ./spec/support/test_site.rb:71:in `block in connected'
         # ./spec/support/test_site.rb:16:in `block in within_reactor'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

Finished in 1.33 seconds (files took 0.27421 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/site/command_spec.rb:177 # RSMP site commands M0001 set yellow flash
rspec ./spec/site/command_spec.rb:185 # RSMP site commands M0001 set dark mode
rspec ./spec/site/command_spec.rb:196 # RSMP site commands M0002 set time plan
```

**Comment by emiltin** [comment]
try latest. please run bundle after updating

**Comment by otterdahl** [comment]
Oh, I just noticed the extra config options in the yaml file I was missing (command_timeout, etc). Running the tests again...

**Comment by otterdahl** [comment]
```
FF.

Failures:

  1) RSMP site commands M0001 set yellow flash
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['status'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0007", "n"=>"status", "status"=>"False,False"}
     # ./spec/site/command_spec.rb:116:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:114:in `each'
     # ./spec/site/command_spec.rb:114:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:112:in `verify_status'
     # ./spec/site/command_spec.rb:147:in `block in switch_normal_control'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:144:in `switch_normal_control'
     # ./spec/site/command_spec.rb:180:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  2) RSMP site commands M0001 set dark mode
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['status'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0007", "n"=>"status", "status"=>"False,False"}
     # ./spec/site/command_spec.rb:116:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:114:in `each'
     # ./spec/site/command_spec.rb:114:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:112:in `verify_status'
     # ./spec/site/command_spec.rb:147:in `block in switch_normal_control'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:144:in `switch_normal_control'
     # ./spec/site/command_spec.rb:191:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

Finished in 6 minutes 9 seconds (files took 0.28131 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/site/command_spec.rb:176 # RSMP site commands M0001 set yellow flash
rspec ./spec/site/command_spec.rb:184 # RSMP site commands M0001 set dark mode
```

**Comment by emiltin** [comment]
Is it correct that it waits for {"sCI"=>"S0007", "n"=>"status", "status"=>"False,False"} when setting NormalControl?

**Comment by otterdahl** [comment]
No, it's the opposite. S0007 means controller switched on (dark mode=false). So it should wait for "True,True"

**Comment by emiltin** [comment]
Then I think you can just change it here:

https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/site/command_spec.rb#L167

**Comment by emiltin** [comment]
Then I think you can just change it here:
https://github.com/rsmp-nordic/rsmp_validator/blob/master/spec/site/command_spec.rb#L167

**Comment by emiltin** [comment]
Btw, note that I added logging to show what the timeout failed to receive:
```
Did not receive status {"sCI"=>"S0007", "n"=>"status", "status"=>"False,False"}
 ```

**Comment by emiltin** [comment]
changed in 596effa in 'refactor' branch. see if this works

**Comment by emiltin** [comment]
There was another S0007 expectation that needed inverting. Pushed to refactor.

**Comment by otterdahl** [comment]
There is a problem with S0005, it's not a multi value. So there is still a problem in 'refactor' branch

Log
```
FF.

Failures:

  1) RSMP site commands M0001 set yellow flash
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['status'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0005", "n"=>"status", "status"=>"False,False"}
     # ./spec/site/command_spec.rb:116:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:114:in `each'
     # ./spec/site/command_spec.rb:114:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:112:in `verify_status'
     # ./spec/site/command_spec.rb:159:in `block in switch_normal_control'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:144:in `switch_normal_control'
     # ./spec/site/command_spec.rb:180:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  2) RSMP site commands M0001 set dark mode
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['status'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0005", "n"=>"status", "status"=>"False,False"}
     # ./spec/site/command_spec.rb:116:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:114:in `each'
     # ./spec/site/command_spec.rb:114:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:112:in `verify_status'
     # ./spec/site/command_spec.rb:159:in `block in switch_normal_control'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:144:in `switch_normal_control'
     # ./spec/site/command_spec.rb:191:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:71:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

Finished in 6 minutes 38 seconds (files took 0.27966 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/site/command_spec.rb:176 # RSMP site commands M0001 set yellow flash
rspec ./spec/site/command_spec.rb:184 # RSMP site commands M0001 set dark mode
```

**Comment by otterdahl** [comment]
This fixes the issue
```
diff --git a/spec/site/command_spec.rb b/spec/site/command_spec.rb
index 03be422..6ce3c19 100644
--- a/spec/site/command_spec.rb
+++ b/spec/site/command_spec.rb
@@ -158,7 +158,7 @@ def switch_normal_control
     # Wait for startup mode to be false
     verify_status({
       description:"start-up mode off",
-      status_list:[{'sCI'=>'S0005','n'=>'status','status'=>multi_value('False')}]
+      status_list:[{'sCI'=>'S0005','n'=>'status','status'=>'False'}]
     })
 
     unsubscribe_from_all
```

**Comment by emiltin** [comment]
cool. all tests green?

**Comment by emiltin** [comment]
pushed the fix to the refactor branch

**Comment by otterdahl** [comment]
Yes. Now everything works

**Comment by emiltin** [comment]
sweet. think i will merge to master then?

**Comment by otterdahl** [comment]
Yes. Go ahead

**Comment by emiltin** [comment]
merged

**Comment by otterdahl** [comment]
How well does it work with the Dynniq tic? Can you print the output log?

**Comment by emiltin** [comment]
the dynniq tlc does not support yellow flash and dark mode. it sends a positive commandresponse, but never actually does anything, as far as i can tell. when running the tests, it therefore ends with a timeout waiting for the relevant statusupdate.
unfortunately i've left for holidays, so i will not be able to show logs until after new years.

**Comment by emiltin** [comment]
outdated, closing
