### ISSUE TITLE
ITC-3 offline for a while?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#300]
The latest run has a lot of failed tests in the beginning, appearently because the TLC doesn't connect, e.g.:

```
Site::Core Connection Sequence is correct for rsmp version 3.1.1
  > Isolating
    2021-11-05T08:42:43.204Z                                                 Stopping supervisor
    2021-11-05T08:42:43.204Z 36222    KK+AG9998=001TC000                          Closing connection to site
    2021-11-05T08:42:43.205Z                                                 Connection to 192.168.200.2:36222 closed
  > Sentinel warning: RSMP::ConnectionError: Connection was closed
    2021-11-05T08:42:43.207Z                                                 Starting supervisor on port 12111
  > Waiting for site to connect
  Failure/Error: @proxy = @node.wait_for_site(:any, config['timeouts']['connect'])
  
  RSMP::TimeoutError:
    No site connected within 120s

  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:233:in `rescue in wait_for_site'
  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:223:in `wait_for_site'
  # ./spec/support/test_site.rb:123:in `wait_for_connection'
  # ./spec/support/testee.rb:61:in `block in isolated'
  # ./spec/support/testee.rb:116:in `block in within_reactor'
  # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:260:in `block in make_fiber'
  # ------------------
  # --- Caused by: ---
  # Async::TimeoutError:
  #   execution expired
  #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:66:in `yield'

Site::Core Connection Sequence is correct for rsmp version 3.1.2
  > Isolating
    2021-11-05T08:44:43.287Z                                                 Stopping supervisor
    2021-11-05T08:44:43.288Z                                                 Starting supervisor on port 12111
  > Waiting for site to connect
  Failure/Error: @proxy = @node.wait_for_site(:any, config['timeouts']['connect'])
  
  RSMP::TimeoutError:
    No site connected within 120s

  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:233:in `rescue in wait_for_site'
  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:223:in `wait_for_site'
  # ./spec/support/test_site.rb:123:in `wait_for_connection'
  # ./spec/support/testee.rb:61:in `block in isolated'
  # ./spec/support/testee.rb:116:in `block in within_reactor'
  # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:260:in `block in make_fiber'
  # ------------------
  # --- Caused by: ---
  # Async::TimeoutError:
  #   execution expired
  #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:66:in `yield'

Site::Core Connection Sequence is correct for rsmp version 3.1.3
  > Isolating
    2021-11-05T08:46:43.300Z                                                 Stopping supervisor
    2021-11-05T08:46:43.301Z                                                 Starting supervisor on port 12111
  > Waiting for site to connect
  Failure/Error: @proxy = @node.wait_for_site(:any, config['timeouts']['connect'])
  
  RSMP::TimeoutError:
    No site connected within 120s

  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:233:in `rescue in wait_for_site'
  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:223:in `wait_for_site'
    No site connected within 120s

  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:233:in `rescue in wait_for_site'
  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:223:in `wait_for_site'
  # ./spec/support/test_site.rb:123:in `wait_for_connection'
  # ./spec/support/testee.rb:31:in `block in connected'
  # ./spec/support/testee.rb:116:in `block in within_reactor'
  # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:260:in `block in make_fiber'
  # ------------------
  # --- Caused by: ---
  # Async::TimeoutError:
  #   execution expired
  #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:66:in `yield'

Site::Traffic Light Controller Clock is used for S0096 response timestamp
  > Waiting for site to connect
  Failure/Error: @proxy = @node.wait_for_site(:any, config['timeouts']['connect'])
  
  RSMP::TimeoutError:
    No site connected within 120s

  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:233:in `rescue in wait_for_site'
  # ./vendor/bundle/ruby/3.0.0/gems/rsmp-0.5.0/lib/rsmp/supervisor.rb:223:in `wait_for_site'
  # ./spec/support/test_site.rb:123:in `wait_for_connection'
  # ./spec/support/testee.rb:31:in `block in connected'
  # ./spec/support/testee.rb:116:in `block in within_reactor'
  # ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:260:in `block in make_fiber'
  # ------------------
  # --- Caused by: ---
  # Async::TimeoutError:
  #   execution expired
  #   ./vendor/bundle/ruby/3.0.0/gems/async-1.29.2/lib/async/task.rb:66:in `yield'
```

**Comment by SwarcoPalm** [comment]
This is now out of date with the new validation setup and could be closed

**Comment by emiltin** [comment]
> This is now out of date with the new validation setup and could be closed

Was progressive reconnect delay disable on the test machine?

**Comment by SwarcoPalm** [comment]
This is not the same test machine, the issue was reported on the test machine situated in Sweden in 2021. The current validator controller is in DK.

**Comment by emiltin** [comment]
OK, closing as we dont' see the issue anymore.
