### ISSUE TITLE
M0022/S0033 state sequence?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_validator#400]
From a vendor:

A question about RSMP Priorities M0022 - S0033, specifically regarding the validator 'Site::Traffic Light Controller Signal Priority state goes through received, activated, completed' test.

From the documentation (SXL 1.2.1) we understood that a priority enters the 'completed' state when it is already in the 'activated' and a cancellation request arrives from the server (validator) with the M0022 command, such as 'cancel'.

The validator expects the sequence received -> activated -> completed but when a priority is in 'activated' state a cancellation request does not arrive. 

I put bellow an extract of the logs of validator. 

Is there any configuration to do in the config file about this or we misunderstood the 'completed' state?

```
Site::Traffic Light Controller Signal Priority state goes through received, activated, completed
    > Subscribing to signal priority request status updates
    2024-07-31T11:09:30.160Z  48722  TRE803               TRE803               342b  Sent StatusSubscribe  {"mType":"rSMsg","type":"StatusSubscribe","cId":"TRE803","sS":[{"sCI":"S0033","n":"status","uRt":"0","sOc":true}],"mId":"342b2ec3-b991-49ab-9b19-1fb5e4900d44","ntsOId":"","xNId":""}
    2024-07-31T11:09:30.160Z  48722  TRE803               -                    -     Collect 2cd8: Waiting for 3 StatusUpdates {:component=>"TRE803"}
    > Send an unrelated signal priority request before
    2024-07-31T11:09:30.165Z  48722  TRE803               TRE803               2149  Sent CommandRequest  {"mType":"rSMsg","type":"CommandRequest","cId":"TRE803","arg":[{"cCI":"M0022","cO":"requestPriority","n":"requestId","v":"402b"},{"cCI":"M0022","cO":"requestPriority","n":"signalGroupId","v":"A"},{"cCI":"M0022","cO":"requestPriority","n":"type","v":"new"},{"cCI":"M0022","cO":"requestPriority","n":"level","v":"7"},{"cCI":"M0022","cO":"requestPriority","n":"eta","v":"2"},{"cCI":"M0022","cO":"requestPriority","n":"vehicleType","v":"car"}],"mId":"2149225b-5880-40d3-8cb3-66d9ed9e94d1","ntsOId":"","xNId":""}
    > Send our signal priority request
    2024-07-31T11:09:30.167Z  48722  TRE803               TRE803               cc5b  Sent CommandRequest  {"mType":"rSMsg","type":"CommandRequest","cId":"TRE803","arg":[{"cCI":"M0022","cO":"requestPriority","n":"requestId","v":"d339"},{"cCI":"M0022","cO":"requestPriority","n":"signalGroupId","v":"A"},{"cCI":"M0022","cO":"requestPriority","n":"type","v":"new"},{"cCI":"M0022","cO":"requestPriority","n":"level","v":"7"},{"cCI":"M0022","cO":"requestPriority","n":"eta","v":"2"},{"cCI":"M0022","cO":"requestPriority","n":"vehicleType","v":"car"}],"mId":"cc5b3ea0-9f01-4c71-8025-de11b78facc6","ntsOId":"","xNId":""}
    > Send an unrelated signal priority request after
    2024-07-31T11:09:30.169Z  48722  TRE803               TRE803               34a8  Sent CommandRequest  {"mType":"rSMsg","type":"CommandRequest","cId":"TRE803","arg":[{"cCI":"M0022","cO":"requestPriority","n":"requestId","v":"5b99"},{"cCI":"M0022","cO":"requestPriority","n":"signalGroupId","v":"A"},{"cCI":"M0022","cO":"requestPriority","n":"type","v":"new"},{"cCI":"M0022","cO":"requestPriority","n":"level","v":"7"},{"cCI":"M0022","cO":"requestPriority","n":"eta","v":"2"},{"cCI":"M0022","cO":"requestPriority","n":"vehicleType","v":"car"}],"mId":"34a8cbf7-5e10-48d7-aa28-c43c948c9cb0","ntsOId":"","xNId":""}
    2024-07-31T11:09:30.180Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B1332-87B1-487B-b87B-0000087B1332", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "b4bb","s": "received","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.180Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B1332-87B1-487B-b87B-0000087B1332"}
    2024-07-31T11:09:30.211Z  48722  TRE803               -                    -     Received MessageAck for StatusUnsubscribe 234b  {"mType": "rSMsg", "type": "MessageAck", "oMId": "234b3142-5c77-439c-8643-12f31757c518"}
    2024-07-31T11:09:30.252Z  48722  TRE803               -                    -     Received MessageAck for StatusSubscribe 342b  {"mType": "rSMsg", "type": "MessageAck", "oMId": "342b2ec3-b991-49ab-9b19-1fb5e4900d44"}
    2024-07-31T11:09:30.253Z  48722  TRE803               -                    -     StatusSubscribe 342b acknowledged, allowing repeated status values for [{"sCI"=>"S0033", "n"=>"status", "uRt"=>"0", "sOc"=>true}]
    2024-07-31T11:09:30.278Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B1341-87B1-487B-b87B-0000087B1341", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "b4bb","s": "queued","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.279Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B1341-87B1-487B-b87B-0000087B1341"}
    2024-07-31T11:09:30.312Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B134D-87B1-487B-b87B-0000087B134D", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "b4bb","s": "activated","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.312Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B134D-87B1-487B-b87B-0000087B134D"}
    2024-07-31T11:09:30.347Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B138B-87B1-487B-b87B-0000087B138B", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [], "q": "recent"}]}
    2024-07-31T11:09:30.348Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B138B-87B1-487B-b87B-0000087B138B"}
    2024-07-31T11:09:30.379Z  48722  TRE803               -                    -     Received MessageAck for CommandRequest 2149  {"mType": "rSMsg", "type": "MessageAck", "oMId": "2149225b-5880-40d3-8cb3-66d9ed9e94d1"}
    2024-07-31T11:09:30.431Z  48722  TRE803               TRE803               087B  Received CommandResponse  {"mType": "rSMsg", "type": "CommandResponse", "mId": "087B138D-87B1-487B-b87B-0000087B138D", "ntsOId": "", "xNId": "", "cId": "TRE803","cTS":"2024-07-31T11:09:29.000Z", "rvs": [{"cCI": "M0022", "n": "requestId", "age": "recent", "v": "402b"}, {"cCI": "M0022", "n": "signalGroupId", "age": "recent", "v": "A"}, {"cCI": "M0022", "n": "type", "age": "recent", "v": "new"}, {"cCI": "M0022", "n": "level", "age": "recent", "v": "7"}, {"cCI": "M0022", "n": "eta", "age": "recent", "v": "2"}, {"cCI": "M0022", "n": "vehicleType", "age": "recent", "v": "car"}]}
    2024-07-31T11:09:30.432Z  48722  TRE803               -                    -     Sent MessageAck for CommandResponse 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B138D-87B1-487B-b87B-0000087B138D"}
    2024-07-31T11:09:30.447Z  48722  TRE803               -                    -     Received MessageAck for CommandRequest cc5b  {"mType": "rSMsg", "type": "MessageAck", "oMId": "cc5b3ea0-9f01-4c71-8025-de11b78facc6"}
    2024-07-31T11:09:30.492Z  48722  TRE803               TRE803               087B  Received CommandResponse  {"mType": "rSMsg", "type": "CommandResponse", "mId": "087B139C-87B1-487B-b87B-0000087B139C", "ntsOId": "", "xNId": "", "cId": "TRE803","cTS":"2024-07-31T11:09:29.000Z", "rvs": [{"cCI": "M0022", "n": "requestId", "age": "recent", "v": "d339"}, {"cCI": "M0022", "n": "signalGroupId", "age": "recent", "v": "A"}, {"cCI": "M0022", "n": "type", "age": "recent", "v": "new"}, {"cCI": "M0022", "n": "level", "age": "recent", "v": "7"}, {"cCI": "M0022", "n": "eta", "age": "recent", "v": "2"}, {"cCI": "M0022", "n": "vehicleType", "age": "recent", "v": "car"}]}
    2024-07-31T11:09:30.492Z  48722  TRE803               -                    -     Sent MessageAck for CommandResponse 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B139C-87B1-487B-b87B-0000087B139C"}
    2024-07-31T11:09:30.515Z  48722  TRE803               -                    -     Received MessageAck for CommandRequest 34a8  {"mType": "rSMsg", "type": "MessageAck", "oMId": "34a8cbf7-5e10-48d7-aa28-c43c948c9cb0"}
    2024-07-31T11:09:30.563Z  48722  TRE803               TRE803               087B  Received CommandResponse  {"mType": "rSMsg", "type": "CommandResponse", "mId": "087B13AB-87B1-487B-b87B-0000087B13AB", "ntsOId": "", "xNId": "", "cId": "TRE803","cTS":"2024-07-31T11:09:29.000Z", "rvs": [{"cCI": "M0022", "n": "requestId", "age": "recent", "v": "5b99"}, {"cCI": "M0022", "n": "signalGroupId", "age": "recent", "v": "A"}, {"cCI": "M0022", "n": "type", "age": "recent", "v": "new"}, {"cCI": "M0022", "n": "level", "age": "recent", "v": "7"}, {"cCI": "M0022", "n": "eta", "age": "recent", "v": "2"}, {"cCI": "M0022", "n": "vehicleType", "age": "recent", "v": "car"}]}
    2024-07-31T11:09:30.568Z  48722  TRE803               -                    -     Sent MessageAck for CommandResponse 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13AB-87B1-487B-b87B-0000087B13AB"}
    2024-07-31T11:09:30.584Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B13C7-87B1-487B-b87B-0000087B13C7", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "402b","s": "received","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.585Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13C7-87B1-487B-b87B-0000087B13C7"}
    2024-07-31T11:09:30.617Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B13D2-87B1-487B-b87B-0000087B13D2", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "d339","s": "received","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.619Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13D2-87B1-487B-b87B-0000087B13D2"}
    > Priority request reached state 'received'
    2024-07-31T11:09:30.619Z  48722  TRE803               -                    -     Collect 2cd8: 1 of 3 message collected
    2024-07-31T11:09:30.651Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B13DE-87B1-487B-b87B-0000087B13DE", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "5b99","s": "received","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.653Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13DE-87B1-487B-b87B-0000087B13DE"}
    2024-07-31T11:09:30.685Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B13EC-87B1-487B-b87B-0000087B13EC", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "402b","s": "activated","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.686Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13EC-87B1-487B-b87B-0000087B13EC"}
    2024-07-31T11:09:30.721Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B13F7-87B1-487B-b87B-0000087B13F7", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "d339","s": "activated","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.722Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B13F7-87B1-487B-b87B-0000087B13F7"}
    > Priority request reached state 'activated'
    2024-07-31T11:09:30.722Z  48722  TRE803               -                    -     Collect 2cd8: 2 of 3 messages collected
    2024-07-31T11:09:30.755Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B1405-87B1-487B-b87B-0000087B1405", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:29.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "5b99","s": "activated","t": "2024-07-31T11:09:29.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:30.756Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B1405-87B1-487B-b87B-0000087B1405"}
    2024-07-31T11:09:31.783Z  48722  TRE803               -                    087B  Received Watchdog  {"mType": "rSMsg", "type": "Watchdog", "mId": "087B1999-87B1-487B-b87B-0000087B1999", "wTs": "2024-07-31T11:09:30.000Z"}
    2024-07-31T11:09:31.784Z  48722  TRE803               -                    -     Sent MessageAck for Watchdog 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B1999-87B1-487B-b87B-0000087B1999"}
    2024-07-31T11:09:39.987Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B39A8-87B3-487B-b87B-0000087B39A8", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:39.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "b4bb","s": "stale","t": "2024-07-31T11:09:39.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:39.988Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B39A8-87B3-487B-b87B-0000087B39A8"}
    2024-07-31T11:09:40.297Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B3ADC-87B3-487B-b87B-0000087B3ADC", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:39.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "402b","s": "stale","t": "2024-07-31T11:09:39.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:40.298Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B3ADC-87B3-487B-b87B-0000087B3ADC"}
    2024-07-31T11:09:40.331Z  48722  TRE803               TRE803               087B  Received StatusUpdate  {"mType": "rSMsg", "type": "StatusUpdate", "mId": "087B3AE9-87B3-487B-b87B-0000087B3AE9", "ntsOId": "TRE803", "xNId": "", "cId": "TRE803", "sTs": "2024-07-31T11:09:39.000Z", "sS": [{"sCI": "S0033", "n": "status", "s": [{"r": "d339","s": "stale","t": "2024-07-31T11:09:39.000Z"}], "q": "recent"}]}
    2024-07-31T11:09:40.332Z  48722  TRE803               -                    -     Sent MessageAck for StatusUpdate 087B  {"mType":"rSMsg","type":"MessageAck","oMId":"087B3AE9-87B3-487B-b87B-0000087B3AE9"}
    > Priority request reached state 'stale'
    2024-07-31T11:09:40.333Z  48722  TRE803               -                    -     Collect 2cd8: Done
    2024-07-31T11:09:40.350Z  48722  TRE803               TRE803               1661  Sent StatusUnsubscribe  {"mType":"rSMsg","type":"StatusUnsubscribe","cId":"TRE803","sS":[{"sCI":"S0033","n":"status"}],"mId":"1661d204-ab9a-442b-9095-c120b61c6d60","ntsOId":"","xNId":""}
  Failure/Error: expect(states).to eq(sequence), "Expected state sequence #{sequence}, got #{states}"
    Expected state sequence ["received", "activated", "completed"], got ["received", "activated", "stale"]

  # /spec/site/tlc/signal_priority_spec.rb:135:in `block (4 levels) in <top (required)>'
  # /spec/support/testee.rb:31:in `connected'
  # /spec/support/test_site.rb:46:in `connected'
  # /spec/site/tlc/signal_priority_spec.rb:62:in `block (3 levels) in <top (required)>'
  # /spec/support/validator.rb:81:in `block in around_each'
  # /usr/local/bundle/gems/async-2.12.0/lib/async/task.rb:164:in `block in run'
  # /usr/local/bundle/gems/async-2.12.0/lib/async/task.rb:377:in `block in schedule'

    state goes through received, activated, completed - Failed: Expected state sequence ["received", "activated", "completed"], got ["received", "activated", "stale"]
```

**Comment by emiltin** [comment]
You're doing it right by setting the request to 'stale' after a while if no cancellation has been received.

The problem is with the test case. It should cancel the request after if has been activated. 

I think we should add a second test case, which checks the timeout behaviour.

Thanks for reporting!
