### ISSUE TITLE
Missing log message when failure due to componentId missmatch

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_validator#6]
When testing status messages I got this output
The test failed due to missmatch of componentId. The requested componendId didn't exist in the controller and it responded with MessageNotAck.

It would be good to output some kind of log message so that is is clear what caused the error

```
$ rspec spec/site/status_spec.rb 
2.81s    error: #<Async::Task:0x2ac12c8f254c (failed)> [pid=7340] [2019-12-06 12:40:18 +0100]
              |   Async::TimeoutError: execution expired
              |   → /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:64 in `yield'
              |     /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/condition.rb:38 in `wait'
              |     /var/lib/gems/2.5.0/gems/rsmp-0.1.4/lib/rsmp/probe.rb:50 in `block in capture'
              |     /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:266 in `with_timeout'
              |     /var/lib/gems/2.5.0/gems/rsmp-0.1.4/lib/rsmp/probe.rb:49 in `capture'
              |     /var/lib/gems/2.5.0/gems/rsmp-0.1.4/lib/rsmp/archive.rb:50 in `capture'
              |     /var/lib/gems/2.5.0/gems/rsmp-0.1.4/lib/rsmp/site_proxy.rb:147 in `wait_for_status_response'
              |     /var/lib/gems/2.5.0/gems/rsmp-0.1.4/lib/rsmp/site_proxy.rb:137 in `request_status'
              |     /home/i0davla/trv/rsmp/rsmp_validator/spec/site/status_spec.rb:11 in `block (3 levels) in <top (required)>'
              |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:55 in `block in connected'
              |     /home/i0davla/trv/rsmp/rsmp_validator/spec/support/test_site.rb:16 in `block in within_reactor'
              |     /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255 in `block in make_fiber'
.

Finished in 2.62 seconds (files took 0.31224 seconds to load)
1 example, 0 failures

```

**Comment by emiltin** [comment]
Good point. For testing, we might need a config file for specifying the components, since they might be different for each piece of equipment you test.

**Comment by emiltin** [comment]
What happens above is that it waits for a StatusResponse, but the site sends NotAck. This is now fixed, so that the test stops waiting if a NotAck is received, and outputs a more meaningful failure message:

```sh
code/rsmp_validator % be rspec spec/site/status_spec.rb
F

Failures:

  1) RSMP site status responds to valid status request
     Failure/Error: expect(response).to be_a(RSMP::StatusResponse)
       expected #<RSMP::MessageNotAck:0x00007ff8223f2128 @timestamp=2019-12-10 08:54:19 UTC, @attributes={"mType"=>"r...,\"n\":\"signalgroupstatus\"}],\"mId\":\"ef3a733c-d524-4089-9d4f-b0ea8665c039\"}", @direction=:out>> to be a kind of RSMP::StatusResponse
     # ./spec/site/status_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:64:in `block in connected'
     # ./spec/support/test_site.rb:16:in `block in within_reactor'
```
