### ISSUE TITLE
TestSite.disconnected throws errors

### ISSUE THREAD

**Issue by GunnarRolander** [rsmp-nordic/rsmp_validator#67]
When using TestSite.disconnected it throws NoMethodError because @supervisor in the within_reactor function is nil.

```
Failure/Error: @supervisor.log "OK", level: :test
NoMethodError:
private method `log' called for nil:NilClass
# ./spec/support/test_site.rb:33:in `within_reactor'
# ./spec/support/test_site.rb:110:in `disconnected'
# ./spec/support/test_site.rb:134:in `disconnected'
```

**Comment by emiltin** [comment]
yes, happens if the test throws an exception while the supervisor is stopped, and therefore deleted. until this is fixed, you can use TestSite.isolated or TestSite.connected in your tests

**Comment by emiltin** [comment]
ps. if you use 3 backticks you can format quotes e.g.

```
Failure/Error: @supervisor.log "OK", level: :test
NoMethodError:
private method `log' called for nil:NilClass

./spec/support/test_site.rb:33:in `within_reactor'

./spec/support/test_site.rb:110:in `disconnected'

./spec/support/test_site.rb:134:in `disconnected'
```
